# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G

# Mod properties
mod_version = 1.0
mod_name = Create: Buildstone Toolkit
mod_id = createbuildstonetoolkit
mod_author = HoshinOFW
mod_description = A Create and Buildstone Toolkit addon aiming to raise the aesthetic ceiling of both mods!
mod_license = Apache License 2.0

# Maven
maven_group = com.github.hoshinofw.createbuildstonetoolkit
archives_name = createbuildstonetoolkit

# Minecraft properties
minecraft_version = 1.20.1

#Parchment
parchment_version = 2023.09.03
use_parchment = true

# Mixins
mixin_version = 0.8.5
mixin_extras_version = 0.4.1

mixin.env.remapRefMap=false
mixin.useLegacyMixin=false
mixin.env.disableTargetValidator=true

# Dependencies
forge_version = 47.1.33
buildstonetoolkit_version = 1.0
architectury_api_version = 9.2.14
create_version = 6.0.7
create_version_number = 205
max_supported_create_version = 6.0.8
ponder_version = 1.0.91
flywheel_version = 1.0.6-beta-266
flywheel_minecraft_version = 1.20.1
vanillin_version = 1.0.0
registrate_version =  MC1.20-1.3.3
jei_minecraft_version = 1.20.1
jei_version = 15.19.0.85
curios_minecraft_version = 1.20.1
curios_version = 5.3.1